Repository jenkinsci/audit-trail-plugin, pull requests merged in 2020-04, with the labels that each got.

#33 [JENKINS-12848] Dump job parameters
  src/main/java/hudson/plugins/audit_trail/AuditTrailRunListener.java
  src/test/java/hudson/plugins/audit_trail/AuditTrailRunListenerTest.java
Labels: feature

#18 Add support for logging to Elastic Search
  README.adoc
  docs/images/jenkins-audit-trail-elastic-search-logger.png
  pom.xml
  src/main/java/hudson/plugins/audit_trail/ElasticSearchAuditLogger.java
  src/main/resources/hudson/plugins/audit_trail/ElasticSearchAuditLogger/config.jelly
  src/main/resources/hudson/plugins/audit_trail/ElasticSearchAuditLogger/help-clientCertificateCredentialsId.html
  src/main/resources/hudson/plugins/audit_trail/ElasticSearchAuditLogger/help-skipCertificateValidation.html
  src/main/resources/hudson/plugins/audit_trail/ElasticSearchAuditLogger/help-url.html
  src/main/resources/hudson/plugins/audit_trail/ElasticSearchAuditLogger/help-usernamePasswordCredentialsId.html
  src/test/java/hudson/plugins/audit_trail/ElasticSearchAuditLoggerTest.java
Labels: feature

#34 [Chore] Fix documentation badge pointing to the wrong plugin
  README.adoc
Labels: documentation

#35 [Chore] Update minimum Jenkins requirement
  pom.xml
Labels: chore, dependencies
